# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxtLWQwcEGfjqXfvDTHRVTaUHT8MEYSU
"""

# app.py — AEGIS Streamlit Dashboard
# Training: CWRU bearing dataset (12 kHz, lab conditions)
# Cross-machine test: IMS bearing dataset (20.48 kHz, run-to-failure)
import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import os

from model import load_model, WINDOW_SIZE
from utils import (
    extract_windows, batch_anomaly_scores, load_mat_signal,
    load_csv_signal, load_ims_snapshot, load_txt_signal,
    resample_to_cwru, extract_features, get_reconstruction,
    classify_severity, classify_ims_health, compute_psd,
    CWRU_SR, IMS_SR, IMS_BEARING_CHANNELS, IMS_FAULT_BEARING,
)

# ─── Page Config ──────────────────────────────────────────────
st.set_page_config(
    page_title="AEGIS — Bearing Fault Detection",
    page_icon="⚙️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Custom CSS ───────────────────────────────────────────────
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem; font-weight: bold;
        color: #1f77b4; text-align: center; padding: 1rem 0;
    }
    .sub-header {
        text-align: center; color: gray;
        font-size: 1.1rem; margin-bottom: 1rem;
    }
    .status-healthy {
        background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
        padding: 1rem; border-radius: 10px; color: white;
        font-size: 1.3rem; font-weight: bold; text-align: center;
    }
    .status-fault {
        background: linear-gradient(135deg, #eb3349 0%, #f45c43 100%);
        padding: 1rem; border-radius: 10px; color: white;
        font-size: 1.3rem; font-weight: bold; text-align: center;
    }
    .status-warning {
        background: linear-gradient(135deg, #f7971e 0%, #ffd200 100%);
        padding: 1rem; border-radius: 10px; color: white;
        font-size: 1.3rem; font-weight: bold; text-align: center;
    }
    .info-box {
        background: #f0f2f6; padding: 1rem; border-radius: 8px;
        border-left: 4px solid #1f77b4; margin: 0.5rem 0;
    }
</style>
""", unsafe_allow_html=True)


# ─── Load Model ──────────────────────────────────────────────
@st.cache_resource
def get_model():
    checkpoint_path = "aegis_model.pt"
    if not os.path.exists(checkpoint_path):
        st.error(f"❌ Model checkpoint not found: {checkpoint_path}")
        st.info("Place `aegis_model.pt` in the same directory as `app.py`")
        st.stop()
    return load_model(checkpoint_path)


model, threshold, device, checkpoint = get_model()


# ─── Sidebar ─────────────────────────────────────────────────
with st.sidebar:
    st.title("⚙️ AEGIS")
    st.caption("Bearing fault detection via reconstruction error")
    st.divider()

    st.subheader("Model Info")
    st.metric("Training Data", "CWRU Normal")
    st.metric("Test Data", "IMS Run-to-Failure")
    st.metric("Window Size", f"{checkpoint.get('window_size', 1024)}")
    st.metric("Training Rate", f"{checkpoint.get('sample_rate', 12000)} Hz")
    st.metric("Threshold (τ)", f"{threshold:.6f}")

    st.divider()

    st.subheader("⚙️ Settings")

    input_sr = st.selectbox(
        "Input signal sample rate",
        options=[
            ("CWRU — 12,000 Hz", CWRU_SR),
            ("IMS — 20,480 Hz", IMS_SR),
            ("Custom", 0),
        ],
        format_func=lambda x: x[0],
        index=0,
        help="Select the sample rate of your uploaded signal"
    )

    if input_sr[1] == 0:
        custom_sr = st.number_input(
            "Custom sample rate (Hz)",
            min_value=1000, max_value=200000, value=12000)
    else:
        custom_sr = input_sr[1]

    tau_multiplier = st.slider(
        "Threshold sensitivity",
        min_value=0.3, max_value=3.0, value=1.0, step=0.05,
        help="< 1.0 = more sensitive (more detections)\n"
             "> 1.0 = less sensitive (fewer false alarms)")
    effective_tau = threshold * tau_multiplier

    ims_bearing = st.selectbox(
        "IMS bearing channel",
        options=list(IMS_BEARING_CHANNELS.keys()),
        index=2,  # default: Bearing 3 (fault bearing)
        help="Select which IMS bearing to analyse. "
             "Bearing 3 develops outer race fault in Test 1."
    )
    ims_channel_idx = IMS_BEARING_CHANNELS[ims_bearing][0]

    st.divider()
    st.caption("Trained on CWRU · Tested on IMS · Research use only")


# ─── Main Header ─────────────────────────────────────────────
st.markdown(
    '<div class="main-header">⚙️ AEGIS Bearing Fault Detection</div>',
    unsafe_allow_html=True)
st.markdown(
    '<div class="sub-header">'
    'Trained on CWRU normal bearings · Cross-machine tested on IMS '
    'run-to-failure data'
    '</div>',
    unsafe_allow_html=True)
st.divider()


# ─── Tabs ────────────────────────────────────────────────────
tab_upload, tab_ims, tab_demo, tab_about = st.tabs([
    "📁 Upload & Analyse",
    "🏭 IMS Batch Analysis",
    "🎯 Live Demo",
    "ℹ️ About",
])


# ═══════════════════════════════════════════════════════════════
# TAB 1: Upload & Analyse (single file)
# ═══════════════════════════════════════════════════════════════
with tab_upload:
    st.subheader("📁 Upload Vibration Data")

    col_up, col_info = st.columns([2, 1])

    with col_up:
        uploaded_file = st.file_uploader(
            "Upload a vibration file",
            type=["mat", "csv", "txt"],
            help="CWRU .mat, IMS snapshot (txt), CSV, "
                 "or any single-channel vibration file")

    with col_info:
        st.markdown("""
        <div class="info-box">
        <b>Supported formats</b><br>
        • <code>.mat</code> — CWRU bearing .mat files<br>
        • <code>.txt</code> — IMS snapshot files (8-column ASCII)<br>
        • <code>.csv</code> — Single-column vibration values<br><br>
        <b>IMS files</b> are auto-detected. Select bearing in sidebar.<br>
        <b>Sample rate</b> is set in sidebar (auto for CWRU/IMS).
        </div>
        """, unsafe_allow_html=True)

    if uploaded_file:
        st.divider()
        st.subheader(f"📄 {uploaded_file.name}")

        file_bytes = uploaded_file.read()
        signal, detected_sr, multi_channel = None, None, None

        ext = uploaded_file.name.lower().split(".")[-1]

        if ext == "mat":
            signal, detected_sr = load_mat_signal(file_bytes,
                                                   uploaded_file.name)
        elif ext == "txt":
            signal, detected_sr, multi_channel = load_txt_signal(file_bytes)
            # If IMS multi-channel, extract selected bearing
            if multi_channel is not None and multi_channel.ndim == 2:
                n_ch = multi_channel.shape[1]
                if ims_channel_idx < n_ch:
                    signal = multi_channel[:, ims_channel_idx]
                    detected_sr = IMS_SR
                    st.info(f"IMS format detected — using {ims_bearing} "
                            f"(channel {ims_channel_idx})")
        elif ext == "csv":
            signal, detected_sr = load_csv_signal(file_bytes)

        if signal is None or len(signal) < WINDOW_SIZE:
            st.error(f"❌ Could not parse file or signal too short "
                     f"(need ≥ {WINDOW_SIZE} samples)")
        else:
            sr = detected_sr if detected_sr else custom_sr

            # Resample if needed
            if sr != CWRU_SR:
                st.info(f"Resampling: {sr:,} Hz → {CWRU_SR:,} Hz")
                signal = resample_to_cwru(signal, sr)

            windows = extract_windows(signal, norm="perwindow")
            n_windows = len(windows)

            if n_windows == 0:
                st.error("❌ No complete windows extracted")
            else:
                with st.spinner("Computing anomaly scores..."):
                    scores = batch_anomaly_scores(model, windows, device)

                mean_score = float(np.mean(scores))
                max_score  = float(np.max(scores))
                pct_fault  = float(np.mean(scores > effective_tau) * 100)

                verdict, _ = classify_severity(mean_score, effective_tau)

                if pct_fault > 50:
                    css = "status-fault"
                elif pct_fault > 10:
                    css = "status-warning"
                else:
                    css = "status-healthy"

                st.markdown(
                    f'<div class="{css}">{verdict} — '
                    f'{pct_fault:.1f}% windows anomalous</div>',
                    unsafe_allow_html=True)

                m1, m2, m3, m4 = st.columns(4)
                m1.metric("Windows", n_windows)
                m2.metric("Mean Score", f"{mean_score:.6f}")
                m3.metric("Threshold (τ)", f"{effective_tau:.6f}")
                m4.metric("Anomalous", f"{pct_fault:.1f}%")

                # ── Plots ────────────────────────────────────
                pc1, pc2 = st.columns(2)

                with pc1:
                    t_axis = np.arange(len(signal)) / CWRU_SR
                    fig_sig = go.Figure()
                    fig_sig.add_trace(go.Scatter(
                        x=t_axis, y=signal, mode="lines",
                        line=dict(width=0.5, color="#1f77b4"),
                        name="Vibration"))
                    fig_sig.update_layout(
                        title="Vibration Signal (after resampling)",
                        xaxis_title="Time (s)",
                        yaxis_title="Amplitude",
                        height=350,
                        margin=dict(l=50, r=20, t=40, b=40))
                    st.plotly_chart(fig_sig, use_container_width=True)

                with pc2:
                    fig_sc = go.Figure()
                    fig_sc.add_trace(go.Scatter(
                        y=scores, mode="lines+markers",
                        marker=dict(
                            size=4,
                            color=["red" if s > effective_tau
                                   else "green" for s in scores]),
                        line=dict(width=1, color="gray"),
                        name="Score"))
                    fig_sc.add_hline(
                        y=effective_tau, line_dash="dash",
                        line_color="red",
                        annotation_text=f"τ = {effective_tau:.4f}")
                    fig_sc.update_layout(
                        title="Anomaly Score per Window",
                        xaxis_title="Window Index",
                        yaxis_title="Reconstruction Error",
                        height=350,
                        margin=dict(l=50, r=20, t=40, b=40))
                    st.plotly_chart(fig_sc, use_container_width=True)

                # PSD
                with st.expander("📈 Power Spectral Density"):
                    freqs, psd = compute_psd(signal, sr=CWRU_SR)
                    fig_psd = go.Figure()
                    fig_psd.add_trace(go.Scatter(
                        x=freqs, y=10 * np.log10(psd + 1e-12),
                        mode="lines",
                        line=dict(width=1, color="#9b59b6")))
                    fig_psd.update_layout(
                        title="Power Spectral Density",
                        xaxis_title="Frequency (Hz)",
                        yaxis_title="Power (dB)",
                        height=300)
                    st.plotly_chart(fig_psd, use_container_width=True)

                # Worst window reconstruction
                with st.expander("🔍 Worst Window — Reconstruction"):
                    worst_idx = int(np.argmax(scores))
                    worst_w   = windows[worst_idx]
                    recon     = get_reconstruction(model, worst_w, device)
                    resid     = np.abs(worst_w - recon)

                    fig_r = make_subplots(
                        rows=2, cols=1,
                        subplot_titles=[
                            f"Window {worst_idx} "
                            f"(Score: {scores[worst_idx]:.6f})",
                            "Reconstruction Residual"],
                        vertical_spacing=0.15)
                    fig_r.add_trace(go.Scatter(
                        y=worst_w, name="Original",
                        line=dict(color="#e74c3c", width=1)),
                        row=1, col=1)
                    fig_r.add_trace(go.Scatter(
                        y=recon, name="Reconstruction",
                        line=dict(color="#2ecc71", width=1, dash="dot")),
                        row=1, col=1)
                    fig_r.add_trace(go.Scatter(
                        y=resid, name="|Residual|", fill="tozeroy",
                        line=dict(color="#e67e22", width=1)),
                        row=2, col=1)
                    fig_r.update_layout(height=500)
                    st.plotly_chart(fig_r, use_container_width=True)

                # Download
                with st.expander("💾 Download Results"):
                    df = pd.DataFrame({
                        "window": range(len(scores)),
                        "anomaly_score": scores,
                        "threshold": effective_tau,
                        "is_anomaly": scores > effective_tau,
                    })
                    st.download_button(
                        "📥 Download CSV", df.to_csv(index=False),
                        file_name=f"aegis_{uploaded_file.name}.csv",
                        mime="text/csv")


# ═══════════════════════════════════════════════════════════════
# TAB 2: IMS Batch Analysis
# ═══════════════════════════════════════════════════════════════
with tab_ims:
    st.subheader("🏭 IMS Run-to-Failure Batch Analysis")

    st.markdown("""
    <div class="info-box">
    <b>IMS Dataset — Test 1</b><br>
    • 4 bearings monitored continuously until failure<br>
    • <b>Bearing 3</b> develops outer race fault<br>
    • Each snapshot: 20,480 samples × 8 channels at 20,480 Hz<br>
    • Upload multiple snapshots to see degradation over time<br>
    • Files are named by timestamp, e.g. <code>2003.10.22.12.06.24</code>
    </div>
    """, unsafe_allow_html=True)

    ims_files = st.file_uploader(
        "Upload IMS snapshot files (select many for degradation curve)",
        type=["txt", "csv"],
        accept_multiple_files=True,
        key="ims_batch",
        help="Upload IMS Test 1 snapshot files. "
             "Select all files in 1st_test/ folder for full analysis.")

    if ims_files:
        # Sort by filename (timestamp-based)
        ims_files_sorted = sorted(ims_files, key=lambda f: f.name)
        n_files = len(ims_files_sorted)

        st.info(f"Processing {n_files} IMS snapshots for "
                f"{ims_bearing} (channel {ims_channel_idx})...")

        progress = st.progress(0, text="Analysing snapshots...")
        snapshot_scores = []
        snapshot_names  = []
        snapshot_features = []

        for idx, f in enumerate(ims_files_sorted):
            file_bytes = f.read()
            sig, sr, multi = load_ims_snapshot(file_bytes, ims_channel_idx)

            if sig is None:
                continue

            # Resample IMS (20480 Hz) → CWRU (12000 Hz)
            sig_resampled = resample_to_cwru(sig, IMS_SR)

            windows = extract_windows(sig_resampled, norm="perwindow")
            if len(windows) == 0:
                continue

            scores = batch_anomaly_scores(model, windows, device)
            mean_sc = float(np.mean(scores))

            snapshot_scores.append(mean_sc)
            snapshot_names.append(f.name)

            feats = extract_features(windows)
            avg_feat = {k: np.mean([ft[k] for ft in feats])
                        for k in feats[0]}
            avg_feat["snapshot"] = f.name
            avg_feat["mean_score"] = mean_sc
            avg_feat["pct_anomalous"] = float(
                np.mean(scores > effective_tau) * 100)
            snapshot_features.append(avg_feat)

            progress.progress(
                (idx + 1) / n_files,
                text=f"Snapshot {idx+1}/{n_files}: {f.name}")

        progress.empty()

        if len(snapshot_scores) == 0:
            st.error("❌ No valid snapshots could be processed")
        else:
            snapshot_scores = np.array(snapshot_scores)

            # ── Summary metrics ──────────────────────────────
            n_anomalous = int(np.sum(snapshot_scores > effective_tau))
            pct_anom    = n_anomalous / len(snapshot_scores) * 100

            sm1, sm2, sm3, sm4 = st.columns(4)
            sm1.metric("Snapshots", len(snapshot_scores))
            sm2.metric("Anomalous", f"{n_anomalous} ({pct_anom:.0f}%)")
            sm3.metric("Mean Score", f"{np.mean(snapshot_scores):.6f}")
            sm4.metric("Max Score", f"{np.max(snapshot_scores):.6f}")

            # ── Degradation curve ─────────────────────────────
            st.subheader("📉 Degradation Curve")
            st.caption(
                "Each point = mean anomaly score of one snapshot. "
                "Rising scores indicate progressive bearing degradation.")

            health_labels = classify_ims_health(snapshot_scores,
                                                effective_tau)
            color_map = {
                "Healthy": "#2ecc71",
                "Degradation": "#f39c12",
                "Fault": "#e74c3c",
            }
            colors = [color_map.get(l, "gray") for l in health_labels]

            fig_deg = go.Figure()

            # Shaded regions
            n_pts = len(snapshot_scores)
            fig_deg.add_vrect(
                x0=0, x1=int(n_pts * 0.5),
                fillcolor="green", opacity=0.05,
                annotation_text="Healthy", annotation_position="top left")
            fig_deg.add_vrect(
                x0=int(n_pts * 0.5), x1=int(n_pts * 0.8),
                fillcolor="orange", opacity=0.05,
                annotation_text="Degradation",
                annotation_position="top left")
            fig_deg.add_vrect(
                x0=int(n_pts * 0.8), x1=n_pts,
                fillcolor="red", opacity=0.05,
                annotation_text="Fault", annotation_position="top left")

            fig_deg.add_trace(go.Scatter(
                y=snapshot_scores, mode="lines+markers",
                marker=dict(size=3, color=colors),
                line=dict(width=1, color="gray"),
                name="Mean Score",
                hovertext=snapshot_names))

            fig_deg.add_hline(
                y=effective_tau, line_dash="dash", line_color="red",
                annotation_text=f"τ = {effective_tau:.4f}")

            fig_deg.update_layout(
                title=f"IMS {ims_bearing} — Degradation Over Time",
                xaxis_title="Snapshot Index (chronological)",
                yaxis_title="Mean Anomaly Score",
                height=450,
                margin=dict(l=50, r=20, t=50, b=40))
            st.plotly_chart(fig_deg, use_container_width=True)

            # ── Feature trends ────────────────────────────────
            with st.expander("📊 Feature Trends Over Time"):
                df_feat = pd.DataFrame(snapshot_features)
                feat_cols = ["RMS", "Kurtosis", "Crest Factor", "Skewness"]

                fig_feat = make_subplots(
                    rows=2, cols=2,
                    subplot_titles=feat_cols,
                    vertical_spacing=0.12,
                    horizontal_spacing=0.08)

                for i, col in enumerate(feat_cols):
                    r, c = divmod(i, 2)
                    fig_feat.add_trace(go.Scatter(
                        y=df_feat[col], mode="lines",
                        line=dict(width=1),
                        name=col), row=r+1, col=c+1)

                fig_feat.update_layout(
                    height=500, showlegend=False,
                    title_text="Statistical Features Over Time")
                st.plotly_chart(fig_feat, use_container_width=True)

            # ── Data table ────────────────────────────────────
            with st.expander("📋 Full Results Table"):
                df_results = pd.DataFrame(snapshot_features)
                df_results["status"] = [
                    "🔴 Anomalous" if s > effective_tau else "✅ Normal"
                    for s in snapshot_scores]
                st.dataframe(df_results, use_container_width=True,
                             height=400)

            # ── Download ──────────────────────────────────────
            with st.expander("💾 Download Results"):
                df_dl = pd.DataFrame({
                    "snapshot": snapshot_names,
                    "mean_score": snapshot_scores,
                    "threshold": effective_tau,
                    "is_anomalous": snapshot_scores > effective_tau,
                    "health_stage": health_labels,
                })
                st.download_button(
                    "📥 Download CSV", df_dl.to_csv(index=False),
                    file_name=f"aegis_ims_{ims_bearing.replace(' ','_')}.csv",
                    mime="text/csv")


# ═══════════════════════════════════════════════════════════════
# TAB 3: Live Demo (synthetic signals)
# ═══════════════════════════════════════════════════════════════
with tab_demo:
    st.subheader("🎯 Live Demo — Synthetic Bearing Signals")
    st.markdown("Test the model without uploading files. "
                "Generates synthetic vibration patterns matching "
                "known fault signatures.")

    dc1, dc2 = st.columns(2)
    with dc1:
        signal_type = st.selectbox(
            "Signal Type",
            ["Normal Bearing",
             "Inner Race Fault (like CWRU IR)",
             "Outer Race Fault (like IMS Bearing 3)",
             "Ball Fault"])
    with dc2:
        noise_level = st.slider("Noise Level", 0.1, 3.0, 1.0, 0.1)
        fault_severity = st.slider("Fault Severity", 0.0, 5.0, 2.0, 0.1)

    if st.button("🚀 Generate & Analyse", type="primary"):
        np.random.seed(42)
        n_samples = CWRU_SR * 2
        t = np.arange(n_samples) / CWRU_SR

        signal = noise_level * np.random.randn(n_samples)
        signal += 0.5 * np.sin(2 * np.pi * 160 * t)

        if "Inner Race" in signal_type:
            bpfi = 5.415 * (1797 / 60)
            for it in np.arange(0, 2, 1.0 / bpfi):
                idx = int(it * CWRU_SR)
                if idx < n_samples - 100:
                    decay = np.exp(-np.arange(100) / 10)
                    signal[idx:idx+100] += (
                        fault_severity * decay *
                        np.sin(2*np.pi*3000*np.arange(100)/CWRU_SR))

        elif "Outer Race" in signal_type:
            bpfo = 3.585 * (1797 / 60)
            for it in np.arange(0, 2, 1.0 / bpfo):
                idx = int(it * CWRU_SR)
                if idx < n_samples - 80:
                    decay = np.exp(-np.arange(80) / 8)
                    signal[idx:idx+80] += (
                        fault_severity * decay *
                        np.sin(2*np.pi*2500*np.arange(80)/CWRU_SR))

        elif "Ball Fault" in signal_type:
            bsf = 1.994 * (1797 / 60)
            for it in np.arange(0, 2, 1.0 / bsf):
                idx = int(it * CWRU_SR)
                if idx < n_samples - 60:
                    decay = np.exp(-np.arange(60) / 6)
                    signal[idx:idx+60] += (
                        fault_severity * decay *
                        np.sin(2*np.pi*2000*np.arange(60)/CWRU_SR))

        windows = extract_windows(signal, norm="perwindow")
        scores  = batch_anomaly_scores(model, windows, device)

        mean_score = float(np.mean(scores))
        pct_fault  = float(np.mean(scores > effective_tau) * 100)
        verdict, _ = classify_severity(mean_score, effective_tau)

        if pct_fault > 50:
            css = "status-fault"
        elif pct_fault > 10:
            css = "status-warning"
        else:
            css = "status-healthy"

        st.markdown(
            f'<div class="{css}">{verdict} — '
            f'{pct_fault:.1f}% anomalous</div>',
            unsafe_allow_html=True)

        mc1, mc2, mc3 = st.columns(3)
        mc1.metric("Mean Score", f"{mean_score:.6f}")
        mc2.metric("Max Score", f"{float(np.max(scores)):.6f}")
        mc3.metric("Anomalous", f"{pct_fault:.1f}%")

        pc1, pc2 = st.columns(2)
        with pc1:
            fig = go.Figure()
            fig.add_trace(go.Scatter(
                x=t, y=signal, mode="lines",
                line=dict(width=0.5, color="#1f77b4")))
            fig.update_layout(
                title=f"Synthetic: {signal_type}",
                xaxis_title="Time (s)", yaxis_title="Amplitude",
                height=350)
            st.plotly_chart(fig, use_container_width=True)

        with pc2:
            fig2 = go.Figure()
            fig2.add_trace(go.Bar(
                y=scores,
                marker_color=["red" if s > effective_tau else "green"
                              for s in scores]))
            fig2.add_hline(
                y=effective_tau, line_dash="dash", line_color="red",
                annotation_text=f"τ={effective_tau:.4f}")
            fig2.update_layout(
                title="Anomaly Scores",
                xaxis_title="Window", yaxis_title="Score",
                height=350)
            st.plotly_chart(fig2, use_container_width=True)


# ═══════════════════════════════════════════════════════════════
# TAB 4: About
# ═══════════════════════════════════════════════════════════════
with tab_about:
    st.subheader("ℹ️ About AEGIS")

    st.markdown("""
    ### Architecture

    AEGIS is a **1D convolutional autoencoder** trained exclusively on
    **normal** bearing vibration data from the **CWRU Bearing Dataset**.
    Faults are detected by measuring reconstruction error — the model
    cannot accurately reconstruct patterns it has never seen.

    ### Training & Evaluation Pipeline

    | Stage | Dataset | Details |
    |-------|---------|---------|
    | **Training** | CWRU | Normal bearings, 0–3 HP, 12 kHz |
    | **Validation** | CWRU | Threshold τ calibrated on val set |
    | **In-distribution test** | CWRU | All 36 fault conditions |
    | **Cross-machine test** | IMS | Different machine, 20.48 kHz, run-to-failure |

    ### IMS Dataset Details

    The **IMS (University of Cincinnati) Bearing Dataset** is a
    run-to-failure experiment:

    - **4 bearings** monitored with accelerometers
    - **Bearing 3** develops **outer race fault**
    - Sampling: 20,480 Hz, 20,480 samples per snapshot
    - Test 1: ~2,000 snapshots over several weeks
    - Data resampled to 12 kHz to match CWRU training

    ### Cross-Machine Protocol

    The model is applied **zero-shot** to IMS data:
    - No retraining on IMS data
    - No threshold re-tuning
    - Signals resampled from 20,480 Hz → 12,000 Hz
    - Per-window z-score normalisation (same as training)

    This tests whether fault patterns learned on CWRU transfer
    to a completely different machine and sensor setup.

    ### CWRU Results (Lab Conditions)

    | Metric | Value |
    |--------|-------|
    | F1 Score | 1.0000 |
    | AUC-ROC | 1.0000 |
    | PR-AUC | 1.0000 |

    > ⚠️ Perfect CWRU scores reflect controlled lab conditions
    > with high SNR. The IMS cross-machine result is the true
    > test of generalisation.

    ### Limitations

    - Trained on one machine type (CWRU motor-driven test rig)
    - Fixed threshold may need adaptation for new machines
    - Not validated on variable-speed conditions
    - Research tool — not production monitoring software
    - IMS evaluation is the only cross-machine validation performed

    ### Key Files

    | File | Purpose |
    |------|---------|
    | `aegis_model.pt` | Trained model weights + threshold |
    | `app.py` | This Streamlit dashboard |
    | `model.py` | AEGIS architecture definition |
    | `utils.py` | Signal processing utilities |
    """)

    st.divider()
    st.caption("AEGIS v1.0 · CWRU-trained · IMS-validated · "
               "Built with PyTorch + Streamlit")