# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vU7qbTAVm0nfXTop8hcATv3PpQpJ7fjG
"""

# app.py — AEGIS Streamlit Dashboard
# Training: CWRU bearing dataset (12 kHz, lab conditions)
# Cross-machine test: IMS bearing dataset (20.48 kHz, run-to-failure)
import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import os
import urllib.request

from model import load_model, WINDOW_SIZE
from utils import (
    extract_windows, batch_anomaly_scores, load_mat_signal,
    load_csv_signal, load_ims_snapshot, load_txt_signal,
    resample_to_cwru, extract_features, get_reconstruction,
    classify_severity, classify_ims_health, compute_psd,
    CWRU_SR, IMS_SR, IMS_BEARING_CHANNELS, IMS_FAULT_BEARING,
)

# ─── Page Config ──────────────────────────────────────────────
st.set_page_config(
    page_title="AEGIS — Bearing Fault Detection",
    page_icon="⚙️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Custom CSS ───────────────────────────────────────────────
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem; font-weight: bold;
        color: #1f77b4; text-align: center; padding: 1rem 0;
    }
    .sub-header {
        text-align: center; color: gray;
        font-size: 1.1rem; margin-bottom: 1rem;
    }
    .status-healthy {
        background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
        padding: 1rem; border-radius: 10px; color: white;
        font-size: 1.3rem; font-weight: bold; text-align: center;
    }
    .status-fault {
        background: linear-gradient(135deg, #eb3349 0%, #f45c43 100%);
        padding: 1rem; border-radius: 10px; color: white;
        font-size: 1.3rem; font-weight: bold; text-align: center;
    }
    .status-warning {
        background: linear-gradient(135deg, #f7971e 0%, #ffd200 100%);
        padding: 1rem; border-radius: 10px; color: white;
        font-size: 1.3rem; font-weight: bold; text-align: center;
    }
    .info-box {
        background: #f0f2f6; padding: 1rem; border-radius: 8px;
        border-left: 4px solid #1f77b4; margin: 0.5rem 0;
    }
</style>
""", unsafe_allow_html=True)


# ─── Built-in Data Helpers ───────────────────────────────────
CWRU_BASE_URL = "https://engineering.case.edu/sites/default/files/"

CWRU_DEMO_FILES = {
    "Normal (0 HP)":           (97,  "Normal", None,  0),
    "Normal (1 HP)":           (98,  "Normal", None,  1),
    "Normal (3 HP)":           (100, "Normal", None,  3),
    "Inner Race 0.007\" (0 HP)": (105, "IR", 0.007, 0),
    "Inner Race 0.007\" (1 HP)": (106, "IR", 0.007, 1),
    "Inner Race 0.014\" (0 HP)": (169, "IR", 0.014, 0),
    "Inner Race 0.021\" (0 HP)": (209, "IR", 0.021, 0),
    "Outer Race 0.007\" (0 HP)": (130, "OR", 0.007, 0),
    "Outer Race 0.014\" (0 HP)": (197, "OR", 0.014, 0),
    "Outer Race 0.021\" (0 HP)": (234, "OR", 0.021, 0),
    "Ball Fault 0.007\" (0 HP)": (118, "BA", 0.007, 0),
    "Ball Fault 0.014\" (0 HP)": (185, "BA", 0.014, 0),
    "Ball Fault 0.021\" (0 HP)": (222, "BA", 0.021, 0),
}


@st.cache_data(show_spinner=False)
def download_cwru_signal(file_num):
    """Download a CWRU .mat file and return the DE_time signal."""
    from scipy.io import loadmat
    import io

    url = f"{CWRU_BASE_URL}{file_num}.mat"
    try:
        response = urllib.request.urlopen(url, timeout=30)
        data = response.read()
        mat = loadmat(io.BytesIO(data))
        de_keys = [k for k in mat if "DE_time" in k
                   and not k.startswith("_")]
        if de_keys:
            return mat[de_keys[0]].flatten().astype(np.float64)
        return None
    except Exception as e:
        st.warning(f"Could not download file {file_num}.mat: {e}")
        return None


def generate_synthetic_signal(signal_type, noise_level=1.0,
                              fault_severity=2.0, duration=2.0):
    """Generate a synthetic bearing vibration signal."""
    np.random.seed(42)
    n_samples = int(CWRU_SR * duration)
    t = np.arange(n_samples) / CWRU_SR

    signal = noise_level * np.random.randn(n_samples)
    signal += 0.5 * np.sin(2 * np.pi * 160 * t)

    if "Inner Race" in signal_type:
        bpfi = 5.415 * (1797 / 60)
        for it in np.arange(0, duration, 1.0 / bpfi):
            idx = int(it * CWRU_SR)
            if idx < n_samples - 100:
                decay = np.exp(-np.arange(100) / 10)
                signal[idx:idx+100] += (
                    fault_severity * decay *
                    np.sin(2*np.pi*3000*np.arange(100)/CWRU_SR))

    elif "Outer Race" in signal_type:
        bpfo = 3.585 * (1797 / 60)
        for it in np.arange(0, duration, 1.0 / bpfo):
            idx = int(it * CWRU_SR)
            if idx < n_samples - 80:
                decay = np.exp(-np.arange(80) / 8)
                signal[idx:idx+80] += (
                    fault_severity * decay *
                    np.sin(2*np.pi*2500*np.arange(80)/CWRU_SR))

    elif "Ball Fault" in signal_type:
        bsf = 1.994 * (1797 / 60)
        for it in np.arange(0, duration, 1.0 / bsf):
            idx = int(it * CWRU_SR)
            if idx < n_samples - 60:
                decay = np.exp(-np.arange(60) / 6)
                signal[idx:idx+60] += (
                    fault_severity * decay *
                    np.sin(2*np.pi*2000*np.arange(60)/CWRU_SR))

    return signal


def analyse_signal(signal, sr, model, device, effective_tau,
                   label="Signal"):
    """Run full analysis on a signal and display results."""
    if sr != CWRU_SR:
        signal = resample_to_cwru(signal, sr)

    windows = extract_windows(signal, norm="perwindow")
    n_windows = len(windows)

    if n_windows == 0:
        st.error("❌ No complete windows extracted")
        return None

    scores = batch_anomaly_scores(model, windows, device)

    mean_score = float(np.mean(scores))
    max_score  = float(np.max(scores))
    pct_fault  = float(np.mean(scores > effective_tau) * 100)

    verdict, _ = classify_severity(mean_score, effective_tau)

    if pct_fault > 50:
        css = "status-fault"
    elif pct_fault > 10:
        css = "status-warning"
    else:
        css = "status-healthy"

    st.markdown(
        f'<div class="{css}">{verdict} — '
        f'{pct_fault:.1f}% windows anomalous</div>',
        unsafe_allow_html=True)

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Windows", n_windows)
    m2.metric("Mean Score", f"{mean_score:.6f}")
    m3.metric("Threshold (τ)", f"{effective_tau:.6f}")
    m4.metric("Anomalous", f"{pct_fault:.1f}%")

    # ── Plots ────────────────────────────────────
    pc1, pc2 = st.columns(2)

    with pc1:
        t_axis = np.arange(len(signal)) / CWRU_SR
        fig_sig = go.Figure()
        fig_sig.add_trace(go.Scatter(
            x=t_axis, y=signal, mode="lines",
            line=dict(width=0.5, color="#1f77b4"),
            name="Vibration"))
        fig_sig.update_layout(
            title=f"Vibration Signal — {label}",
            xaxis_title="Time (s)",
            yaxis_title="Amplitude",
            height=350,
            margin=dict(l=50, r=20, t=40, b=40))
        st.plotly_chart(fig_sig, use_container_width=True)

    with pc2:
        fig_sc = go.Figure()
        fig_sc.add_trace(go.Scatter(
            y=scores, mode="lines+markers",
            marker=dict(
                size=4,
                color=["red" if s > effective_tau
                       else "green" for s in scores]),
            line=dict(width=1, color="gray"),
            name="Score"))
        fig_sc.add_hline(
            y=effective_tau, line_dash="dash",
            line_color="red",
            annotation_text=f"τ = {effective_tau:.4f}")
        fig_sc.update_layout(
            title="Anomaly Score per Window",
            xaxis_title="Window Index",
            yaxis_title="Reconstruction Error",
            height=350,
            margin=dict(l=50, r=20, t=40, b=40))
        st.plotly_chart(fig_sc, use_container_width=True)

    # Score distribution
    fig_dist = go.Figure()
    fig_dist.add_trace(go.Histogram(
        x=scores, nbinsx=50, name="Scores",
        marker_color="#1f77b4", opacity=0.7))
    fig_dist.add_vline(
        x=effective_tau, line_dash="dash",
        line_color="red",
        annotation_text=f"τ = {effective_tau:.4f}")
    fig_dist.update_layout(
        title="Score Distribution",
        xaxis_title="Anomaly Score",
        yaxis_title="Count",
        height=300,
        margin=dict(l=50, r=20, t=40, b=40))
    st.plotly_chart(fig_dist, use_container_width=True)

    # PSD
    with st.expander("📈 Power Spectral Density"):
        freqs, psd = compute_psd(signal, sr=CWRU_SR)
        fig_psd = go.Figure()
        fig_psd.add_trace(go.Scatter(
            x=freqs, y=10 * np.log10(psd + 1e-12),
            mode="lines",
            line=dict(width=1, color="#9b59b6")))
        fig_psd.update_layout(
            title="Power Spectral Density",
            xaxis_title="Frequency (Hz)",
            yaxis_title="Power (dB)",
            height=300)
        st.plotly_chart(fig_psd, use_container_width=True)

    # Worst window reconstruction
    with st.expander("🔍 Worst Window — Reconstruction Detail"):
        worst_idx = int(np.argmax(scores))
        worst_w   = windows[worst_idx]
        recon     = get_reconstruction(model, worst_w, device)
        resid     = np.abs(worst_w - recon)

        fig_r = make_subplots(
            rows=2, cols=1,
            subplot_titles=[
                f"Window {worst_idx} "
                f"(Score: {scores[worst_idx]:.6f})",
                "Reconstruction Residual"],
            vertical_spacing=0.15)
        fig_r.add_trace(go.Scatter(
            y=worst_w, name="Original",
            line=dict(color="#e74c3c", width=1)),
            row=1, col=1)
        fig_r.add_trace(go.Scatter(
            y=recon, name="Reconstruction",
            line=dict(color="#2ecc71", width=1, dash="dot")),
            row=1, col=1)
        fig_r.add_trace(go.Scatter(
            y=resid, name="|Residual|", fill="tozeroy",
            line=dict(color="#e67e22", width=1)),
            row=2, col=1)
        fig_r.update_layout(height=500)
        st.plotly_chart(fig_r, use_container_width=True)

    # Features table
    with st.expander("📊 Statistical Features per Window"):
        features = extract_features(windows)
        df_feat = pd.DataFrame(features)
        df_feat.insert(0, "Window", range(len(features)))
        df_feat["Anomaly Score"] = scores
        df_feat["Status"] = [
            "🔴 Fault" if s > effective_tau else "✅ Normal"
            for s in scores]
        st.dataframe(df_feat, use_container_width=True, height=300)

    # Download
    with st.expander("💾 Download Results"):
        df = pd.DataFrame({
            "window": range(len(scores)),
            "anomaly_score": scores,
            "threshold": effective_tau,
            "is_anomaly": scores > effective_tau,
        })
        st.download_button(
            "📥 Download CSV", df.to_csv(index=False),
            file_name=f"aegis_{label.replace(' ', '_')}.csv",
            mime="text/csv")

    return scores


# ─── Load Model ──────────────────────────────────────────────
@st.cache_resource
def get_model():
    checkpoint_path = "aegis_model.pt"
    if not os.path.exists(checkpoint_path):
        st.error(f"❌ Model checkpoint not found: {checkpoint_path}")
        st.info("Place `aegis_model.pt` in the same directory "
                "as `app.py`")
        st.stop()
    return load_model(checkpoint_path)


model, threshold, device, checkpoint = get_model()


# ─── Sidebar ─────────────────────────────────────────────────
with st.sidebar:
    st.title("⚙️ AEGIS")
    st.caption("Bearing fault detection via reconstruction error")
    st.divider()

    st.subheader("Model Info")
    st.metric("Training Data", "CWRU Normal")
    st.metric("Test Data", "IMS Run-to-Failure")
    st.metric("Window Size",
              f"{checkpoint.get('window_size', 1024)}")
    st.metric("Training Rate",
              f"{checkpoint.get('sample_rate', 12000)} Hz")
    st.metric("Threshold (τ)", f"{threshold:.6f}")

    st.divider()

    st.subheader("⚙️ Settings")

    tau_multiplier = st.slider(
        "Threshold sensitivity",
        min_value=0.3, max_value=3.0, value=1.0, step=0.05,
        help="< 1.0 = more sensitive (more detections)\n"
             "> 1.0 = less sensitive (fewer false alarms)")
    effective_tau = threshold * tau_multiplier

    st.divider()
    st.caption("Trained on CWRU · Tested on IMS · Research use only")


# ─── Main Header ─────────────────────────────────────────────
st.markdown(
    '<div class="main-header">⚙️ AEGIS Bearing Fault Detection'
    '</div>',
    unsafe_allow_html=True)
st.markdown(
    '<div class="sub-header">'
    'Trained on CWRU normal bearings · Cross-machine tested on '
    'IMS run-to-failure data · No upload required'
    '</div>',
    unsafe_allow_html=True)
st.divider()


# ─── Tabs ────────────────────────────────────────────────────
tab_cwru, tab_compare, tab_synth, tab_upload, tab_about = st.tabs([
    "🔬 CWRU Live Test",
    "⚔️ Normal vs Fault",
    "🎯 Synthetic Demo",
    "📁 Upload (Optional)",
    "ℹ️ About",
])


# ═══════════════════════════════════════════════════════════════
# TAB 1: CWRU Live Test — Downloads real data automatically
# ═══════════════════════════════════════════════════════════════
with tab_cwru:
    st.subheader("🔬 CWRU Bearing Data — Live from Source")
    st.markdown("""
    Select any CWRU bearing condition below. The data is
    **downloaded automatically** from Case Western Reserve
    University's server — no upload needed.
    """)

    selected = st.selectbox(
        "Select bearing condition",
        options=list(CWRU_DEMO_FILES.keys()),
        index=0,
        help="Data is downloaded live from CWRU servers")

    file_num, ftype, severity, load = CWRU_DEMO_FILES[selected]

    col_info1, col_info2, col_info3 = st.columns(3)
    col_info1.info(f"**Type:** {ftype}")
    if severity:
        col_info2.info(f"**Severity:** {severity}\"")
    else:
        col_info2.info("**Severity:** N/A")
    col_info3.info(f"**Load:** {load} HP")

    if st.button("🚀 Analyse This Bearing", type="primary",
                 key="cwru_analyse"):
        with st.spinner(f"Downloading {file_num}.mat from CWRU..."):
            signal = download_cwru_signal(file_num)

        if signal is not None:
            st.success(f"✅ Downloaded {len(signal):,} samples "
                       f"({len(signal)/CWRU_SR:.1f}s at {CWRU_SR:,} Hz)")
            analyse_signal(signal, CWRU_SR, model, device,
                          effective_tau, label=selected)
        else:
            st.error("❌ Could not download data. "
                     "Check internet connection.")


# ═══════════════════════════════════════════════════════════════
# TAB 2: Side-by-side Normal vs Fault comparison
# ═══════════════════════════════════════════════════════════════
with tab_compare:
    st.subheader("⚔️ Normal vs Fault — Side-by-Side Comparison")
    st.markdown("""
    Automatically downloads and compares a **normal** bearing
    against a **faulty** bearing. See exactly how AEGIS
    distinguishes them.
    """)

    col_n, col_f = st.columns(2)
    with col_n:
        normal_choice = st.selectbox(
            "Normal bearing",
            [k for k in CWRU_DEMO_FILES if "Normal" in k],
            index=0, key="compare_normal")
    with col_f:
        fault_choice = st.selectbox(
            "Faulty bearing",
            [k for k in CWRU_DEMO_FILES if "Normal" not in k],
            index=3, key="compare_fault")

    if st.button("⚔️ Compare Now", type="primary",
                 key="compare_btn"):
        fn_n = CWRU_DEMO_FILES[normal_choice][0]
        fn_f = CWRU_DEMO_FILES[fault_choice][0]

        with st.spinner("Downloading both signals..."):
            sig_n = download_cwru_signal(fn_n)
            sig_f = download_cwru_signal(fn_f)

        if sig_n is not None and sig_f is not None:
            win_n = extract_windows(sig_n, norm="perwindow")
            win_f = extract_windows(sig_f, norm="perwindow")

            sc_n = batch_anomaly_scores(model, win_n, device)
            sc_f = batch_anomaly_scores(model, win_f, device)

            # Verdict
            c1, c2 = st.columns(2)
            with c1:
                pct_n = float(np.mean(sc_n > effective_tau) * 100)
                v_n, _ = classify_severity(
                    float(np.mean(sc_n)), effective_tau)
                css_n = ("status-fault" if pct_n > 50
                         else "status-warning" if pct_n > 10
                         else "status-healthy")
                st.markdown(
                    f'<div class="{css_n}">{normal_choice}<br>'
                    f'{v_n} — {pct_n:.1f}% anomalous</div>',
                    unsafe_allow_html=True)
                st.metric("Mean Score",
                          f"{float(np.mean(sc_n)):.6f}")
                st.metric("Windows", len(sc_n))

            with c2:
                pct_f = float(np.mean(sc_f > effective_tau) * 100)
                v_f, _ = classify_severity(
                    float(np.mean(sc_f)), effective_tau)
                css_f = ("status-fault" if pct_f > 50
                         else "status-warning" if pct_f > 10
                         else "status-healthy")
                st.markdown(
                    f'<div class="{css_f}">{fault_choice}<br>'
                    f'{v_f} — {pct_f:.1f}% anomalous</div>',
                    unsafe_allow_html=True)
                st.metric("Mean Score",
                          f"{float(np.mean(sc_f)):.6f}")
                st.metric("Windows", len(sc_f))

            # Overlaid score distribution
            fig_comp = go.Figure()
            fig_comp.add_trace(go.Histogram(
                x=sc_n, nbinsx=50, name=normal_choice,
                marker_color="#2ecc71", opacity=0.6))
            fig_comp.add_trace(go.Histogram(
                x=sc_f, nbinsx=50, name=fault_choice,
                marker_color="#e74c3c", opacity=0.6))
            fig_comp.add_vline(
                x=effective_tau, line_dash="dash",
                line_color="black",
                annotation_text=f"τ = {effective_tau:.4f}")
            fig_comp.update_layout(
                title="Score Distribution — Normal vs Fault",
                xaxis_title="Anomaly Score",
                yaxis_title="Count",
                barmode="overlay",
                height=400)
            st.plotly_chart(fig_comp, use_container_width=True)

            # Side-by-side waveforms
            st.subheader("Waveform Comparison")
            wc1, wc2 = st.columns(2)
            with wc1:
                t_n = np.arange(min(len(sig_n), 12000)) / CWRU_SR
                fig_wn = go.Figure()
                fig_wn.add_trace(go.Scatter(
                    x=t_n, y=sig_n[:len(t_n)],
                    mode="lines",
                    line=dict(width=0.5, color="#2ecc71")))
                fig_wn.update_layout(
                    title=f"{normal_choice} (first 1s)",
                    xaxis_title="Time (s)",
                    yaxis_title="Amplitude",
                    height=300)
                st.plotly_chart(fig_wn, use_container_width=True)

            with wc2:
                t_f = np.arange(min(len(sig_f), 12000)) / CWRU_SR
                fig_wf = go.Figure()
                fig_wf.add_trace(go.Scatter(
                    x=t_f, y=sig_f[:len(t_f)],
                    mode="lines",
                    line=dict(width=0.5, color="#e74c3c")))
                fig_wf.update_layout(
                    title=f"{fault_choice} (first 1s)",
                    xaxis_title="Time (s)",
                    yaxis_title="Amplitude",
                    height=300)
                st.plotly_chart(fig_wf, use_container_width=True)

            # Separation metric
            separation = (float(np.mean(sc_f)) -
                         float(np.mean(sc_n)))
            st.info(f"**Score separation:** {separation:.6f} "
                    f"(fault mean − normal mean). "
                    f"Larger = better discrimination.")

        else:
            st.error("❌ Could not download one or both signals.")


# ═══════════════════════════════════════════════════════════════
# TAB 3: Synthetic Demo
# ═══════════════════════════════════════════════════════════════
with tab_synth:
    st.subheader("🎯 Synthetic Bearing Signals")
    st.markdown("Generate synthetic vibration patterns matching "
                "known fault signatures. **No data needed.**")

    dc1, dc2 = st.columns(2)
    with dc1:
        signal_type = st.selectbox(
            "Signal Type",
            ["Normal Bearing",
             "Inner Race Fault",
             "Outer Race Fault",
             "Ball Fault"],
            key="synth_type")
    with dc2:
        noise_level = st.slider(
            "Noise Level", 0.1, 3.0, 1.0, 0.1,
            key="synth_noise")
        fault_severity = st.slider(
            "Fault Severity", 0.0, 5.0, 2.0, 0.1,
            key="synth_sev")

    if st.button("🚀 Generate & Analyse", type="primary",
                 key="synth_btn"):
        signal = generate_synthetic_signal(
            signal_type, noise_level, fault_severity)
        analyse_signal(signal, CWRU_SR, model, device,
                      effective_tau, label=f"Synthetic {signal_type}")


# ═══════════════════════════════════════════════════════════════
# TAB 4: Upload (Optional)
# ═══════════════════════════════════════════════════════════════
with tab_upload:
    st.subheader("📁 Upload Your Own Data (Optional)")
    st.markdown("""
    <div class="info-box">
    <b>This tab is optional.</b> Use the other tabs to test
    AEGIS without uploading anything.<br><br>
    <b>Supported formats:</b><br>
    • <code>.mat</code> — CWRU bearing .mat files<br>
    • <code>.txt</code> — IMS snapshot files (8-column ASCII)<br>
    • <code>.csv</code> — Single-column vibration values
    </div>
    """, unsafe_allow_html=True)

    input_sr = st.selectbox(
        "Signal sample rate",
        options=[
            ("CWRU — 12,000 Hz", CWRU_SR),
            ("IMS — 20,480 Hz", IMS_SR),
            ("Custom", 0),
        ],
        format_func=lambda x: x[0],
        index=0,
        key="upload_sr")

    if input_sr[1] == 0:
        custom_sr = st.number_input(
            "Custom sample rate (Hz)",
            min_value=1000, max_value=200000, value=12000)
    else:
        custom_sr = input_sr[1]

    uploaded_file = st.file_uploader(
        "Upload a vibration file",
        type=["mat", "csv", "txt"],
        help="CWRU .mat, IMS snapshot (txt), CSV")

    if uploaded_file:
        file_bytes = uploaded_file.read()
        signal, detected_sr = None, None

        ext = uploaded_file.name.lower().split(".")[-1]
        if ext == "mat":
            signal, detected_sr = load_mat_signal(
                file_bytes, uploaded_file.name)
        elif ext == "txt":
            signal, detected_sr, multi = load_txt_signal(file_bytes)
        elif ext == "csv":
            signal, detected_sr = load_csv_signal(file_bytes)

        if signal is not None and len(signal) >= WINDOW_SIZE:
            sr = detected_sr if detected_sr else custom_sr
            analyse_signal(signal, sr, model, device,
                          effective_tau, label=uploaded_file.name)
        else:
            st.error("❌ Could not parse file or signal too short")


# ═══════════════════════════════════════════════════════════════
# TAB 5: About
# ═══════════════════════════════════════════════════════════════
with tab_about:
    st.subheader("ℹ️ About AEGIS")

    st.markdown("""
    ### How It Works

    1. **Select** a bearing condition (or use built-in data)
    2. Signal is **windowed** into 1024-sample non-overlapping
       segments
    3. Each window is **z-score normalised**
    4. The autoencoder **reconstructs** each window
    5. **Mean squared error** = anomaly score
    6. Windows with score > threshold (τ) = **anomalous**

    ### Training & Evaluation

    | Stage | Dataset | Details |
    |-------|---------|---------|
    | **Training** | CWRU | Normal bearings, 0–3 HP, 12 kHz |
    | **Validation** | CWRU | Threshold τ calibrated on val set |
    | **In-distribution** | CWRU | All 36 fault conditions |
    | **Cross-machine** | IMS | Different machine, 20.48 kHz |

    ### CWRU Results

    | Metric | Value |
    |--------|-------|
    | F1 Score | 1.0000 |
    | AUC-ROC | 1.0000 |
    | PR-AUC | 1.0000 |
    | FPR | 0.0000 |

    > ⚠️ Perfect CWRU scores reflect controlled lab conditions.
    > Cross-machine evaluation (IMS) is the true generalisation
    > test.

    ### Key Features of This App

    - **🔬 CWRU Live Test** — Downloads real bearing data
      automatically from CWRU servers
    - **⚔️ Normal vs Fault** — Side-by-side comparison with
      overlaid score distributions
    - **🎯 Synthetic Demo** — Adjustable fault type, severity,
      and noise level
    - **📁 Upload** — Optional, for testing your own data

    ### Limitations

    - Trained on one machine type (CWRU)
    - Fixed threshold may need adaptation for new machines
    - Not validated on variable-speed conditions
    - Research tool, not production monitoring
    """)

    st.divider()
    st.caption("AEGIS v1.0 · CWRU-trained · IMS-validated · "
               "Built with PyTorch + Streamlit")