# -*- coding: utf-8 -*-
"""model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UxSWOvJSUn2L1NWHJ8F8IrXdfyVDH6Y4
"""

# model.py — AEGIS model architecture (matches training notebook)
import torch
import torch.nn as nn

WINDOW_SIZE = 1024


class Conv1DBlock(nn.Module):
    def __init__(self, in_ch, out_ch, kernel, pool=2, dropout=0.1):
        super().__init__()
        pad = kernel // 2
        self.block = nn.Sequential(
            nn.Conv1d(in_ch, out_ch, kernel, padding=pad),
            nn.BatchNorm1d(out_ch),
            nn.ReLU(),
            nn.MaxPool1d(pool),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.block(x)


class ConvTranspose1DBlock(nn.Module):
    def __init__(self, in_ch, out_ch, kernel, stride=2):
        super().__init__()
        pad = kernel // 2
        out_pad = stride - 1
        self.block = nn.Sequential(
            nn.ConvTranspose1d(in_ch, out_ch, kernel,
                               stride=stride, padding=pad,
                               output_padding=out_pad),
            nn.BatchNorm1d(out_ch),
            nn.ReLU(),
        )

    def forward(self, x):
        return self.block(x)


class AEGIS(nn.Module):
    """
    1D Convolutional Autoencoder for bearing fault detection.
    Trained on CWRU normal bearing data (12 kHz).
    Evaluated zero-shot on IMS bearings (20.48 kHz, resampled).
    """

    def __init__(self, window_size=WINDOW_SIZE):
        super().__init__()
        self.window_size = window_size
        self.encoder = nn.Sequential(
            Conv1DBlock(1, 32, 7, pool=2, dropout=0.1),
            Conv1DBlock(32, 64, 5, pool=2, dropout=0.1),
            Conv1DBlock(64, 128, 3, pool=2, dropout=0.1),
        )
        self.decoder = nn.Sequential(
            ConvTranspose1DBlock(128, 64, 3, stride=2),
            ConvTranspose1DBlock(64, 32, 5, stride=2),
            ConvTranspose1DBlock(32, 1, 7, stride=2),
        )
        self.output_layer = nn.Sequential(
            nn.Conv1d(1, 1, kernel_size=1),
            nn.Sigmoid(),
        )

    def forward(self, x):
        z = self.encoder(x)
        xhat = self.decoder(z)[:, :, :self.window_size]
        return self.output_layer(xhat)

    def encode(self, x):
        with torch.no_grad():
            return self.encoder(x)

    def anomaly_score(self, x):
        with torch.no_grad():
            return torch.mean((x - self.forward(x)) ** 2, dim=(1, 2))


def load_model(checkpoint_path="aegis_model.pt"):
    """Load trained AEGIS model from checkpoint."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    checkpoint = torch.load(checkpoint_path, map_location=device,
                            weights_only=False)
    model = AEGIS(window_size=checkpoint.get("window_size", WINDOW_SIZE))
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval().to(device)
    threshold = checkpoint["threshold_cwru"]
    return model, threshold, device, checkpoint