# -*- coding: utf-8 -*-
"""utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UYEKSnMSoK_hCFvyPfm4uNlPGr0uqUCO
"""

# utils.py — Preprocessing and analysis utilities
# Designed for CWRU (training) and IMS (cross-machine evaluation)
import numpy as np
from scipy.io import loadmat
from scipy.signal import resample, welch
from scipy.stats import kurtosis, skew
import torch

WINDOW_SIZE  = 1024
CWRU_SR      = 12_000   # CWRU sample rate (Hz) — training domain
IMS_SR       = 20_480   # IMS sample rate (Hz)  — test domain

# ── IMS Dataset Constants ─────────────────────────────────────
# IMS Test 1: 4 bearings, 8 channels (2 per bearing)
# Bearing 3 (channels 5-6) develops outer race fault
# Files: space-separated ASCII, 20480 samples per channel per snapshot
IMS_BEARING_CHANNELS = {
    "Bearing 1": [0, 1],
    "Bearing 2": [2, 3],
    "Bearing 3": [4, 5],   # develops fault
    "Bearing 4": [6, 7],
}
IMS_FAULT_BEARING = "Bearing 3"


def zscore_normalise(window, eps=1e-8):
    """Per-window z-score normalisation."""
    mu, sigma = window.mean(), window.std()
    return (window - mu) / (sigma + eps)


def extract_windows(signal, window_size=WINDOW_SIZE, norm="perwindow"):
    """Extract non-overlapping windows from a signal."""
    windows = []
    for start in range(0, len(signal) - window_size + 1, window_size):
        w = signal[start: start + window_size].astype(np.float32)
        if norm == "perwindow":
            w = zscore_normalise(w)
        windows.append(w)
    return (np.array(windows, dtype=np.float32) if windows
            else np.empty((0, window_size), dtype=np.float32))


def resample_to_cwru(signal, src_sr, tgt_sr=CWRU_SR):
    """Resample signal to match CWRU sample rate (12 kHz)."""
    if src_sr == tgt_sr:
        return signal
    n_target = int(len(signal) * tgt_sr / src_sr)
    return resample(signal, n_target).astype(np.float64)


def batch_anomaly_scores(model, windows, device, batch_size=256):
    """Compute anomaly scores for all windows."""
    model.eval()
    t = torch.FloatTensor(windows).unsqueeze(1).to(device)
    scores = []
    with torch.no_grad():
        for i in range(0, len(t), batch_size):
            scores.append(
                model.anomaly_score(t[i: i + batch_size]).cpu().numpy())
    return np.concatenate(scores)


def get_reconstruction(model, window, device):
    """Get reconstruction of a single window."""
    model.eval()
    t = torch.FloatTensor(window).unsqueeze(0).unsqueeze(0).to(device)
    with torch.no_grad():
        rec = model(t).squeeze().cpu().numpy()
    return rec


# ── File Loaders ──────────────────────────────────────────────

def load_mat_signal(file_bytes, filename="uploaded.mat"):
    """
    Load vibration signal from .mat file bytes.
    Handles CWRU format (DE_time key).
    """
    import io
    mat = loadmat(io.BytesIO(file_bytes))

    # CWRU format: look for DE_time key
    de_keys = [k for k in mat if "DE_time" in k and not k.startswith("_")]
    if de_keys:
        return mat[de_keys[0]].flatten().astype(np.float64), CWRU_SR

    # Fallback: find the largest numeric array
    best_key, best_len = None, 0
    for k in mat:
        if k.startswith("_"):
            continue
        try:
            arr = np.array(mat[k]).flatten()
            if len(arr) > best_len:
                best_len = len(arr)
                best_key = k
        except Exception:
            continue

    if best_key and best_len > 1000:
        return mat[best_key].flatten().astype(np.float64), None

    return None, None


def load_csv_signal(file_bytes):
    """Load vibration signal from CSV file bytes."""
    import io, csv

    text = file_bytes.decode("utf-8", errors="ignore")
    reader = csv.reader(io.StringIO(text))

    values = []
    for row in reader:
        for val in row:
            try:
                values.append(float(val.strip()))
            except ValueError:
                continue

    if len(values) > 100:
        return np.array(values, dtype=np.float64), None
    return None, None


def load_ims_snapshot(file_bytes, bearing_channel=4):
    """
    Load a single IMS snapshot file.

    IMS files are space-separated ASCII with 8 columns
    (2 channels × 4 bearings). Each column has 20480 samples.

    Default channel=4 → Bearing 3, channel 1 (the fault bearing).
    """
    import io
    text = file_bytes.decode("utf-8", errors="ignore")
    lines = text.strip().split("\n")

    all_channels = []
    for line in lines:
        parts = line.strip().split()
        try:
            vals = [float(v) for v in parts]
            all_channels.append(vals)
        except ValueError:
            continue

    if not all_channels:
        return None, None, None

    data = np.array(all_channels, dtype=np.float64)

    if data.ndim == 1:
        return data, IMS_SR, None

    n_channels = data.shape[1]

    if bearing_channel < n_channels:
        signal = data[:, bearing_channel]
    else:
        signal = data[:, 0]

    return signal, IMS_SR, data


def load_txt_signal(file_bytes):
    """Load vibration signal from space/tab-separated text file."""
    import io
    text = file_bytes.decode("utf-8", errors="ignore")
    lines = text.strip().split("\n")

    # First try: could be IMS format (multi-column)
    first_line = lines[0].strip().split()
    if len(first_line) >= 4:
        # Likely IMS or multi-channel — use load_ims_snapshot
        return load_ims_snapshot(file_bytes)

    # Single column
    values = []
    for line in lines:
        parts = line.strip().split()
        for val in parts:
            try:
                values.append(float(val))
            except ValueError:
                continue

    if len(values) > 100:
        return np.array(values, dtype=np.float64), None, None
    return None, None, None


# ── Feature Extraction ────────────────────────────────────────

def extract_features(windows):
    """Extract statistical features from windows."""
    out = []
    for w in windows:
        rms  = float(np.sqrt(np.mean(w ** 2)))
        kurt = float(kurtosis(w, fisher=True))
        peak = float(np.max(np.abs(w)))
        cf   = peak / (rms + 1e-8)
        sk   = float(skew(w))
        out.append({"RMS": rms, "Kurtosis": kurt,
                     "Crest Factor": cf, "Skewness": sk})
    return out


def compute_psd(signal, sr=CWRU_SR, nperseg=1024):
    """Compute power spectral density."""
    freqs, psd = welch(signal, fs=sr, nperseg=nperseg)
    return freqs, psd


# ── Severity Classification ──────────────────────────────────

def classify_severity(score, tau):
    """Classify anomaly severity based on score relative to threshold."""
    ratio = score / (tau + 1e-8)
    if ratio < 0.5:
        return "✅ Healthy", "green"
    elif ratio < 0.8:
        return "🟡 Watch", "orange"
    elif ratio < 1.0:
        return "🟠 Warning", "darkorange"
    elif ratio < 2.0:
        return "🔴 Fault Detected", "red"
    else:
        return "🔴 Severe Fault", "darkred"


def classify_ims_health(scores, tau, early_pct=0.5, late_pct=0.2):
    """
    Classify IMS bearing health progression.

    In IMS Test 1:
    - First ~50% of snapshots = healthy
    - Last ~20% = clear fault
    - Middle = degradation zone
    """
    n = len(scores)
    labels = []
    for i in range(n):
        pct = i / max(n - 1, 1)
        if pct < early_pct:
            labels.append("Healthy")
        elif pct > (1.0 - late_pct):
            labels.append("Fault")
        else:
            labels.append("Degradation")
    return labels